export const USER_ALL_LOADING_TRUE = "USER_ALL_LOADING_TRUE";
export const USER_ALL_LOADING_FALSE = "USER_ALL_LOADING_FALSE";

export const GET_SEARCH_USER_ALL_DETAIL_REQUEST =
  "GET_SEARCH_USER_ALL_DETAIL_REQUEST";

export const GET_SEARCH_USER_ALL_DETAIL_REQUEST_SUCCESS =
  "GET_SEARCH_USER_ALL_DETAIL_REQUEST_SUCCESS";

export const GET_SEARCH_USER_ALL_DETAIL_REQUEST_ERROR =
  "GET_SEARCH_USER_ALL_DETAIL_REQUEST_ERROR";
