export const GET_SIGNUP_REQUEST="GET_SIGNUP_REQUEST";
export const GET_SIGNUP_SUCCESS="GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_ERROR="GET_SIGNUP_ERROR";


export const GET_LOGIN_REQUEST="GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS="GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR="GET_LOGIN_ERROR";

export const SIGN_OUT="SIGN_OUT";